# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2025 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_CPU_QOS_ARBITER) += oplus_bsp_freq_qos_arbiter.o

oplus_bsp_freq_qos_arbiter-y := qos_arbiter.o

obj-$(CONFIG_OPLUS_FEATURE_CPU_QOS_ARBITER_TEST) += qos_arbiter_test.o
